@host = localhost:8090

// Register User
POST http://{{host}}/api/user/register HTTP/1.1
content-type: application/json
    
{
    "name": "Kirana Yus Malita",
    "username": "kiranay99",
    "email": "kiranay@go.com",
    "password": "123465789"
}

###